language: c

sudo: true

compiler:
  - gcc

addons:
  apt:
    packages:
      - build-essential
      - apache2
      - php5
      - php5-gd
      - libgd-dev
      - unzip
      - lcov
      - gperf
      - gcovr

script:
  - ./configure --enable-testing
  - |
    if [[ "true" == "true" ]]; then
      somerealtime=$(date +%s)
      realtimeresult=$?
      somebadtime=$(date s)
      badtimeresult=$?
      echo "real: $realtimeresult, bad: $badtimeresult"
    fi
  - make all && cd t-tap && make test_checks && ./test_checks


