language: c

sudo: true

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - build-essential
            - apache2
            - php5
            - php5-gd
            - libgd-dev
            - unzip
            - lcov
            - gperf
            - gcovr
      env:
        - MATRIX_EVAL="CC=gcc"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - apache2
            - php5
            - php5-gd
            - libgd-dev
            - unzip
            - lcov
            - gperf
            - gcovr
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./configure --enable-testing
  - make test
  - gcovr -r .
